// Mock data for the application

export const mockProjects = [
  {
    id: 1,
    name: "Forest Restoration Initiative",
    location: "Western Ghats, Karnataka",
    description: "Restoring native forest ecosystems to protect biodiversity and prevent soil erosion",
    status: "active",
    progress: 75,
    totalClaims: 12,
    verifiedClaims: 9,
    image: "/forest-restoration-area.jpg",
    impact: "2,500 saplings planted, 15 hectares restored",
    carbonOffset: "450 tons CO2/year",
  },
  {
    id: 2,
    name: "Urban Tree Plantation",
    location: "Delhi NCR",
    description: "Large-scale urban tree plantation to improve air quality and reduce urban heat",
    status: "active",
    progress: 60,
    totalClaims: 8,
    verifiedClaims: 5,
    image: "/tree-planting-volunteers.jpg",
    impact: "1,200 trees planted, 8 parks restored",
    carbonOffset: "320 tons CO2/year",
  },
  {
    id: 3,
    name: "Community Nursery Development",
    location: "Rajasthan",
    description: "Establishing community nurseries for native species propagation and distribution",
    status: "active",
    progress: 90,
    totalClaims: 15,
    verifiedClaims: 14,
    image: "/nursery-saplings.jpg",
    impact: "50,000 saplings grown, 25 villages engaged",
    carbonOffset: "180 tons CO2/year",
  },
  {
    id: 4,
    name: "Watershed Forest Protection",
    location: "Himachal Pradesh",
    description: "Protecting and restoring watershed forests for water conservation and biodiversity",
    status: "pending",
    progress: 30,
    totalClaims: 6,
    verifiedClaims: 2,
    image: "/forest-canopy-sunlight.jpg",
    impact: "500 hectares protected, 3 watersheds restored",
    carbonOffset: "600 tons CO2/year",
  },
]

export const mockClaims = [
  {
    id: 1,
    projectId: 1,
    type: "Saplings Planted",
    quantity: 500,
    unit: "saplings",
    description: "Planted 500 native tree saplings in the designated forest area",
    status: "pending",
    submittedAt: "2024-01-15T10:30:00Z",
    location: "Western Ghats Sector A",
    photos: ["/forest-saplings-planted.jpg"],
    ngoName: "Green Forest Foundation",
  },
  {
    id: 2,
    projectId: 2,
    type: "Tree Plantation",
    quantity: 50,
    unit: "trees",
    description: "Planted mature trees in urban park areas for immediate impact",
    status: "verified",
    submittedAt: "2024-01-14T14:20:00Z",
    verifiedAt: "2024-01-15T09:15:00Z",
    location: "Central Park Delhi",
    photos: ["/urban-tree-planting.jpg"],
    ngoName: "Forest Conservation Trust",
  },
  {
    id: 3,
    projectId: 3,
    type: "Seedlings Prepared",
    quantity: 1000,
    unit: "seedlings",
    description: "Prepared native species seedlings in community nursery",
    status: "pending",
    submittedAt: "2024-01-15T16:45:00Z",
    location: "Village Nursery Center",
    photos: ["/nursery-seedling-preparation.jpg"],
    ngoName: "Rural Forest Initiative",
  },
]

export const mockTasks = [
  {
    id: 1,
    claimId: 1,
    title: "Verify Forest Plantation",
    description: "Verify 500 saplings planted at Western Ghats Sector A",
    location: "Western Ghats, Karnataka",
    distance: "2.3 km",
    reward: 150,
    priority: "high",
    estimatedTime: "2 hours",
    coordinates: { lat: 15.3173, lng: 75.7139 },
    ngoName: "Green Forest Foundation",
    submittedAt: "2024-01-15T10:30:00Z",
  },
  {
    id: 2,
    claimId: 3,
    title: "Verify Nursery Development",
    description: "Verify 1000 seedlings prepared at Village Nursery",
    location: "Village Nursery, Rajasthan",
    distance: "5.7 km",
    reward: 100,
    priority: "medium",
    estimatedTime: "1.5 hours",
    coordinates: { lat: 27.0238, lng: 74.2179 },
    ngoName: "Rural Forest Initiative",
    submittedAt: "2024-01-15T16:45:00Z",
  },
]

export const mockUserStats = {
  ngo: {
    totalProjects: 3,
    activeClaims: 5,
    verifiedClaims: 28,
    reputation: 4.7,
    impactScore: 1250,
  },
  verifier: {
    totalVerifications: 127,
    reputation: 4.8,
    monthlyEarnings: 2400,
    completionRate: 96,
  },
}
