// Mock data for the application

export const mockProjects = [
  {
    id: 1,
    name: "Mangrove Restoration",
    location: "Sundarbans, West Bengal",
    description: "Restoring mangrove forests to protect coastal communities and marine biodiversity",
    status: "active",
    progress: 75,
    totalClaims: 12,
    verifiedClaims: 9,
    image: "/mangrove-conservation.jpg",
    impact: "2,500 saplings planted, 15 hectares restored",
    carbonOffset: "450 tons CO2/year",
  },
  {
    id: 2,
    name: "Coral Reef Protection",
    location: "Andaman Islands",
    description: "Protecting and restoring coral reef ecosystems through transplantation",
    status: "active",
    progress: 60,
    totalClaims: 8,
    verifiedClaims: 5,
    image: "/coral-restoration-hero.jpg",
    impact: "200 coral fragments transplanted, 5 reef sites restored",
    carbonOffset: "120 tons CO2/year",
  },
  {
    id: 3,
    name: "Beach Cleanup Initiative",
    location: "Marina Beach, Chennai",
    description: "Regular beach cleanup and plastic waste removal with community engagement",
    status: "active",
    progress: 90,
    totalClaims: 15,
    verifiedClaims: 14,
    image: "/beach-cleanup-team.jpg",
    impact: "5,000 kg plastic removed, 500 volunteers engaged",
    carbonOffset: "80 tons CO2/year",
  },
  {
    id: 4,
    name: "Marine Biodiversity Survey",
    location: "Goa Coastal Waters",
    description: "Comprehensive marine life documentation and protection program",
    status: "pending",
    progress: 30,
    totalClaims: 6,
    verifiedClaims: 2,
    image: "/marine-biodiversity.jpg",
    impact: "150 species documented, 3 new habitats identified",
    carbonOffset: "200 tons CO2/year",
  },
]

export const mockClaims = [
  {
    id: 1,
    projectId: 1,
    type: "Saplings Planted",
    quantity: 500,
    unit: "saplings",
    description: "Planted 500 mangrove saplings in the designated area",
    status: "pending",
    submittedAt: "2024-01-15T10:30:00Z",
    location: "Sundarbans Sector A",
    photos: ["/mangrove-saplings-planted.jpg"],
    ngoName: "Green Earth Foundation",
  },
  {
    id: 2,
    projectId: 2,
    type: "Coral Transplantation",
    quantity: 50,
    unit: "coral fragments",
    description: "Transplanted healthy coral fragments to damaged reef areas",
    status: "verified",
    submittedAt: "2024-01-14T14:20:00Z",
    verifiedAt: "2024-01-15T09:15:00Z",
    location: "Havelock Island Reef Site",
    photos: ["/coral-transplantation-underwater.jpg"],
    ngoName: "Ocean Conservation Trust",
  },
  {
    id: 3,
    projectId: 3,
    type: "Waste Collected",
    quantity: 250,
    unit: "kg",
    description: "Collected plastic waste and debris from beach area",
    status: "pending",
    submittedAt: "2024-01-15T16:45:00Z",
    location: "Marina Beach North",
    photos: ["/beach-waste-collection-bags.jpg"],
    ngoName: "Clean Coast Initiative",
  },
]

export const mockTasks = [
  {
    id: 1,
    claimId: 1,
    title: "Verify Mangrove Plantation",
    description: "Verify 500 saplings planted at Sundarbans Sector A",
    location: "Sundarbans, West Bengal",
    distance: "2.3 km",
    reward: 150,
    priority: "high",
    estimatedTime: "2 hours",
    coordinates: { lat: 21.9497, lng: 88.4297 },
    ngoName: "Green Earth Foundation",
    submittedAt: "2024-01-15T10:30:00Z",
  },
  {
    id: 2,
    claimId: 3,
    title: "Verify Beach Cleanup",
    description: "Verify 250kg waste collection at Marina Beach",
    location: "Marina Beach, Chennai",
    distance: "5.7 km",
    reward: 100,
    priority: "medium",
    estimatedTime: "1.5 hours",
    coordinates: { lat: 13.0475, lng: 80.2824 },
    ngoName: "Clean Coast Initiative",
    submittedAt: "2024-01-15T16:45:00Z",
  },
]

export const mockUserStats = {
  ngo: {
    totalProjects: 3,
    activeClaims: 5,
    verifiedClaims: 28,
    reputation: 4.7,
    impactScore: 1250,
  },
  verifier: {
    totalVerifications: 127,
    reputation: 4.8,
    monthlyEarnings: 2400,
    completionRate: 96,
  },
}
